### ISSUE TITLE
Log File size limitation

### ISSUE THREAD

**Issue by ghost** [Arthur-Milchior/anki-note-deletion#1]
When deleting huge decks, the log file size becomes unreasonably big. 
I deleted a ~20000 card deck and got a 22gb log file.

**Comment by Arthur-Milchior** [comment]
Honestly, it makes no sens at all too many. I'm going to ask a few question, because right now I can't help.

By «log file» you mean deleted.txt right ?
Do you know how many note there is ? Because as the name state, it logs deletion of notes and not of cards. I'll still assume that there are around 10 000 notes.

By any luck, do you have any idea how big was your log before ? I assume that you don't, because honestly there is no reason to keep track of this. Unless you have a backup system. That would be wonderful.

Could you maybe copy me the last ten lines of the file deleted.txt 
If you are on a unix system (i.e. mac or linux mostly), you can use the command line in your profile folder,  and enter the comand
tail deleted.txt
to obtain them


Because honestly it makes no sens at all. It means 2.2 mega by note. 
Each line of the file is supposed to contai the  content of the note deleted, and its identification number, and the reason for deletion. Unless you have notes with millions of character you won't have line which weight 2.2 mega !

One last request. 
Open a backup before you deleted this. 
Delete the deck. Check how much giga it added.
Then disable the add-on, open again the back-up. Delete again. And check whether there is really a difference.

**Comment by ghost** [comment]
Hey. Sorry for the late reply. Unfortunately I don't have that deck on hand and so I did it with [this](https://drive.google.com/file/d/1qsgFUxvLO87MhwlNms_CTs0AnlSvLZtQ/view?usp=drive_open) deck with fresh log files.

Deletion with your addon enabled
![dopus_2019-03-24_13-10-41](https://user-images.githubusercontent.com/13769570/54876950-2fce4000-4e10-11e9-8ffa-61a6586bbe74.png)

Deletion with your addon disabled
![dopus_2019-03-24_13-32-08](https://user-images.githubusercontent.com/13769570/54876940-13320800-4e10-11e9-8c7f-267b469e50e7.png)

Here's the last 9  lines of the log
[Last 10 lines.txt](https://github.com/Arthur-Milchior/anki-note-deletion/files/3000200/Last.10.lines.txt)

**Comment by Arthur-Milchior** [comment]
No trouble. You're the one with the problem, not me.
May I also ask you to export one note and send it to me.

You can use https://ankiweb.net/shared/info/1983204951 to select a single card and export it. (Disclosure: I wrote this add-on)

According to this file, the note containing:
What is the mechanism of action of cromolyn and nedocromil in the treatment of asthma?`As mast cell stabilizers, these drugs prevent release of inflammatory mediators from mast cells``Respiratory::Pharmacology::Asthma drugs
contains 13893 cards. I assume I don't really have to ask whether your note type have so many card type. I have note type with 200 card type, and anki is slow, there is no way on earth you could have anki working correctly with so many card for a single note

If you see any thing similar to 13893 it may be a hint. For example, i may imagine that it is the number of card in your collection. Could you please check that ?

**Comment by Arthur-Milchior** [comment]
I found the bug. I'm going to correct this soon. Thank you for letting me know this bug. 
13893 was probably the number of cards you had in the deck you deleted. I never did delete a deck so big, so even if I had the bug, it was not noticeable.  I'm really sorry. I don't really know how to repare your log however, because I can't really download such a big file, and I'm not sure enough that I can write a script which would clean your log without removing some important informations from it.

**Comment by ghost** [comment]
You're off by one. 13894 was the total number. 
It's no issue at all. The above log file was for a test profile I chuck stuff in before moving to my main profile. 
Thank you for your time.

**Comment by Arthur-Milchior** [comment]
I think I counted the number of commas separating id of card deleted.  I should have added one since there is no comma before the first element. My bad. 
Well, if there are no other problem, I guess that's acceptable.

Thank you for reporting the bug to me. I may not even have noticed it myself for a long time, and you are maybe not the only one having the same error (this add-on was downloaded only 40 times, so I guess it's not so bad)
